
# Author
title: Jinho Ko
image: /public/profile.jpeg
image_wide: /public/profile-wide.png
email: ben4945@postech.ac.kr
github: https://github.com/dgggit
linkedin: http://www.linkedin.com/in/jinhoko
facebook: https://www.facebook.com/ben4945
description: >
  B.S., dept. of Creative IT Engineering, POSTECH, Korea
baseurl: "" 
url: "http://dgggit.github.io/" 
github_username:  dgggit

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed


show_drafts : true

# plugins
mathjax: true
google_analytics: 'UA-156068228-1'