
# Author
title: Jinho Ko
image: /public/jhko.png
email: ben4945@postech.ac.kr
description: >
  Undergraduate, dept. of Creative IT Engineering, POSTECH, Korea
baseurl: "" 
url: "http://dgggit.github.io/" 
github_username:  dgggit

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# header
header_pages:
  - index.md
  - about.md
  - techblog.html
  - CV.html

show_drafts : true

# plugins
mathjax: true
google_analytics: 'UA-156068228-1'